# prefixキーをC-jに変更する
set -g prefix C-j

# デフォルトのprefixキーC-bを解除する
unbind C-b

## ペインのキーバインド

bind C-i split-window -h
bind C-k split-window -v

# ペインの移動
bind C-j select-pane -t :.+

# ペインを最大化
bind C-z resize-pane -Z
bind -n C-z resize-pane -Z

# ペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

unbind -n C-h
unbind -n C-k
unbind -n C-l
unbind x

bind C-q copy-mode

# ウィンドウを切り替える
bind C-c new-window
bind C-p previous-window
bind C-n next-window
bind C-l last-window
bind C-w choose-window

# prefix+r で設定のリロード
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind-key C-x kill-pane


bind C-b if-shell '[ "$(tmux show -gv window-style | sed "s/.*bg=//")" = "default" ]' \
  'set -g window-style fg=default,bg=colour236; set -g window-active-style fg=default,bg=colour234; set -g pane-border-style fg=colour240,bg=colour236; set -g pane-active-border-style fg=green,bg=colour234' \
  'set -g window-style fg=default,bg=default; set -g window-active-style fg=default,bg=default; set -g pane-border-style fg=colour240,bg=default; set -g pane-active-border-style fg=green,bg=default'
